/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formhotel;

import javax.swing.JOptionPane;
import models.Users;

/**
 *
 * @author ASUS
 */
public class Front extends javax.swing.JFrame {
    Users user = new Users();

    /**
     * Creates new form Front
     */
    public Front() {
        initComponents();
        menumasterhotel.setEnabled(false);
        menutransaksi.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUname = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        labelpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        butlogin = new javax.swing.JButton();
        labelnama = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menumasterhotel = new javax.swing.JMenuItem();
        menukeluar = new javax.swing.JMenuItem();
        menutransaksi = new javax.swing.JMenu();
        menutranshot = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelUname.setText("Username");

        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });

        labelpassword.setText("Password");

        butlogin.setText("Login");
        butlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butloginActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        menumasterhotel.setText("Master Hotel");
        menumasterhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menumasterhotelActionPerformed(evt);
            }
        });
        jMenu1.add(menumasterhotel);

        menukeluar.setText("Keluar");
        menukeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menukeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menukeluar);

        jMenuBar1.add(jMenu1);

        menutransaksi.setText("Transaksi");

        menutranshot.setText("Transaksi Pemesanan");
        menutranshot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutranshotActionPerformed(evt);
            }
        });
        menutransaksi.add(menutranshot);

        jMenuBar1.add(menutransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelnama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUname)
                            .addComponent(labelpassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butlogin)
                            .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelnama)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUname)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpassword)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(butlogin)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menukeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menukeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menukeluarActionPerformed

    private void menumasterhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menumasterhotelActionPerformed
        // TODO add your handling code here:
        hotel hotel = new hotel();
        hotel.setVisible(true);
    }//GEN-LAST:event_menumasterhotelActionPerformed

    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void butloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butloginActionPerformed
        // TODO add your handling code here:
        String uname = txtUname.getText();
        String pass = String.valueOf(txtpassword.getPassword());
        int count = user.checkUser(uname, pass);
        if(uname.equals("admin")&& pass.equals("adminadmin")|| count>0){
            menumasterhotel.setEnabled(true);
            menutransaksi.setEnabled(true);
            
            labelUname.setVisible(false);
            labelpassword.setVisible(false);
            txtUname.setVisible(false);
            txtpassword.setVisible(false);
            butlogin.setVisible(false);
            labelnama.setText("Selamat datang, "+uname);
            
           
        }
        else{
            JOptionPane.showMessageDialog(null, "User tidak ditemukan");
        }
    }//GEN-LAST:event_butloginActionPerformed

    private void menutranshotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutranshotActionPerformed
        // TODO add your handling code here:
        transaksi transaksi = new transaksi();
        transaksi.setVisible(true);
    }//GEN-LAST:event_menutranshotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butlogin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelUname;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JMenuItem menukeluar;
    private javax.swing.JMenuItem menumasterhotel;
    private javax.swing.JMenu menutransaksi;
    private javax.swing.JMenuItem menutranshot;
    private javax.swing.JTextField txtUname;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
