/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formhotel;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author HarryHarkespan
 */
public class transaksi extends javax.swing.JFrame {
    static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://127.0.0.1/test?autoReconnect=true&useSSL=false";
    static final String USER = "root";
    static final String PASS = "";
    
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;
    /**
     * Creates new form Barang
     */
    public transaksi() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnokmr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtSimpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        tblUpdate = new javax.swing.JButton();
        tblDelete = new javax.swing.JButton();
        tblClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datein = new javax.swing.JTextField();
        dateout = new javax.swing.JTextField();
        txtbockam = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtlama = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Kode Kamar");

        jLabel2.setText("No Kamar");

        jLabel3.setText("Jenis Kamar");

        txtjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjenisActionPerformed(evt);
            }
        });

        jLabel4.setText("Total");

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        txtSimpan.setText("Simpan");
        txtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpanActionPerformed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "kode", "nomor", "jenis", "checkIn", "chechOut", "lamaNginap", "total"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);

        jScrollPane3.setViewportView(jScrollPane2);

        tblUpdate.setText("Update");
        tblUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUpdateActionPerformed(evt);
            }
        });

        tblDelete.setText("Hapus");
        tblDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDeleteActionPerformed(evt);
            }
        });

        tblClear.setText("Kosongkan");
        tblClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblClearActionPerformed(evt);
            }
        });

        jLabel5.setText("Check IN");

        jLabel6.setText("Check OUT");

        datein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateinActionPerformed(evt);
            }
        });

        dateout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateoutActionPerformed(evt);
            }
        });

        txtbockam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Room", "Deluxe Room", "Double Room", "Skuyy Room" }));
        txtbockam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbockamActionPerformed(evt);
            }
        });

        jLabel7.setText("Lama Menginap");

        txtlama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtSimpan)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tblUpdate)
                                .addGap(40, 40, 40)
                                .addComponent(tblDelete)
                                .addGap(34, 34, 34)
                                .addComponent(tblClear))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtlama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbockam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateout, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datein, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnokmr, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKode, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnokmr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbockam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtlama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSimpan)
                    .addComponent(tblUpdate)
                    .addComponent(tblDelete)
                    .addComponent(tblClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpanActionPerformed
        // TODO add your handling code here:
        String kode = txtKode.getText().toString().trim();
        int nokmar = Integer.parseInt(txtnokmr.getText());
        String jeniskmr = txtbockam.getSelectedItem().toString().trim();
        String checkin = datein.getText();
        String checkout = dateout.getText();
        int lama = Integer.parseInt(txtlama.getText());

    // Menghitung total harga
        int hargaPerHari = 0;
        if (jeniskmr.equals("Single Room")) {
        hargaPerHari = 1000000;
        } else if (jeniskmr.equals("Deluxe Room")) {
        hargaPerHari = 2000000;
        } else if (jeniskmr.equals("Double Room")) {
        hargaPerHari = 3000000;
        } else if (jeniskmr.equals("Skuyy Room")) {
            hargaPerHari = 4000000;
        }

        int total = hargaPerHari * lama;
        txttotal.setText(String.valueOf(total));
        insert(kode,nokmar,jeniskmr,checkin,checkout,lama,total);
        showtable();
        clear();
        
    }//GEN-LAST:event_txtSimpanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        showtable();
 
    }//GEN-LAST:event_formWindowOpened

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        getData();
    }//GEN-LAST:event_tabelDataMouseClicked

    private void tblClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_tblClearActionPerformed

    private void tblUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUpdateActionPerformed
        // TODO add your handling code here:
        String kode = txtKode.getText().toString().trim();
        int nokmar = Integer.parseInt(txtnokmr.getText());
        String jeniskmr = txtbockam.getSelectedItem().toString().trim();
        String checkin = datein.getText();
        String checkout = dateout.getText();
        int lama = Integer.parseInt(txtlama.getText());
        int total = Integer.parseInt(txttotal.getText());

    // Menghitung total harga
        int hargaPerHari = 0;
        if (jeniskmr.equals("Single Room")) {
        hargaPerHari = 1000000;
        } else if (jeniskmr.equals("Deluxe Room")) {
        hargaPerHari = 2000000;
        } else if (jeniskmr.equals("Double Room")) {
        hargaPerHari = 3000000;
        } else if (jeniskmr.equals("Skuyy Room")) {
            hargaPerHari = 4000000;
        }
        
        int Htotal = hargaPerHari * lama;
        txttotal.setText(String.valueOf(total));
        update(kode,nokmar,jeniskmr,checkin,checkout,lama,total);
        showtable();
        clear();
        total();
    }//GEN-LAST:event_tblUpdateActionPerformed

    private void tblDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDeleteActionPerformed
        // TODO add your handling code here:
        String kode = txtKode.getText().toString().trim();
        try {
            Class.forName(JDBC_DRIVER);
   
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
 
            stmt = conn.createStatement();
            
            String sql = "DELETE FROM transaksi WHERE kd_kmr=?";
            
            PreparedStatement pms = conn.prepareStatement(sql);
            pms.setString(1, kode);
            
            pms.execute();
            
            stmt.close();
            conn.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        showtable();
        clear();
    }//GEN-LAST:event_tblDeleteActionPerformed

    private void dateinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateinActionPerformed

    private void txtbockamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbockamActionPerformed
        // TODO add your handling code here:
        String nilaijenis = (String)txtbockam.getSelectedItem();
        String teks;
        teks = "";
        
        switch(nilaijenis){
            case "Single Room":
                teks = " Rp. 1000000";
                break;
            case "Deluxe Room":
                teks = " Rp. 2000000";
                break;
            case "Double Room":
                teks = " Rp. 3000000";
                break;
            case "Skuyy Room":
                teks = " Rp. 4000000";
                break;   

        }
        txtjenis.setText(teks);
       
    }//GEN-LAST:event_txtbockamActionPerformed

    private void dateoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateoutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dateoutActionPerformed

    private void txtlamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlamaActionPerformed
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_txtlamaActionPerformed

    private void txtjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjenisActionPerformed
        // TODO add your handling code here:
        

                                         
    }//GEN-LAST:event_txtjenisActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
      

    }//GEN-LAST:event_txttotalActionPerformed

    public void getData(){
        int baris = tabelData.getSelectedRow();
        txtKode.setText(String.valueOf(tabelData.getValueAt(baris,0)));
        txtnokmr.setText(String.valueOf(tabelData.getValueAt(baris,1)));
        txtbockam.setSelectedItem(String.valueOf(tabelData.getValueAt(baris, 2)));
        datein.setText(String.valueOf(tabelData.getValueAt(baris, 3)));
        dateout.setText(String.valueOf(tabelData.getValueAt(baris, 4)));
        txtlama.setText(String.valueOf(tabelData.getValueAt(baris, 5)));
        txttotal.setText(String.valueOf(tabelData.getValueAt(baris, 6)));
        
    }
    
    public void insert(String kode, int nokmar, String jeniskmar, String checkin, String checkout,int lama, int total) {
    try {
        Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL, USER, PASS);
        stmt = conn.createStatement();

        // Mengecek apakah kode barang sudah ada di database
        String checkQuery = "SELECT * FROM transaksi WHERE kd_kmr = ?";
        PreparedStatement checkStatement = conn.prepareStatement(checkQuery);
        checkStatement.setString(1, kode);
        ResultSet checkResult = checkStatement.executeQuery();

        if (checkResult.next()) {
            // Kode barang sudah ada, tampilkan pesan dialog
            JOptionPane.showMessageDialog(this, "Kode Kamar sudah ada!");
        } else {
            // Kode barang belum ada, lakukan operasi INSERT
            String insertQuery = "INSERT INTO transaksi (kd_kmr, no_kmr, jenis_kmr,check_in,check_oout,lama,total) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement insertStatement = conn.prepareStatement(insertQuery);
            insertStatement.setString(1, kode);
            insertStatement.setInt(2, nokmar);
            insertStatement.setString(3, jeniskmar);
            insertStatement.setString(4, checkin);
            insertStatement.setString(5, checkout);
            insertStatement.setInt(6, lama);
            insertStatement.setInt(7, total);

            insertStatement.execute();
        }

        stmt.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    public void showtable(){
        try{
            Class.forName(JDBC_DRIVER);	   
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Kode Kamar");
            model.addColumn("No Kamar");
            model.addColumn("Jenis Kamar");
            model.addColumn("Check IN");
            model.addColumn("Check OUT");
            model.addColumn("Lama Menginap");
            model.addColumn("Total");
        
 
            stmt = conn.createStatement();
            String sql = "SELECT * FROM transaksi";
            //int i = 1;
            rs = stmt.executeQuery(sql);
            while(rs.next()) {
            	String kode= rs.getString("kd_kmr");
            	int nomor = rs.getInt("no_kmr");
            	String jenis = rs.getString("jenis_kmr");
                String checkIn=rs.getString("check_in");
                String checkOut=rs.getString("check_oout");
                int lamaNginap=rs.getInt("lama");
            	int total=rs.getInt("total");
                model.addRow (new Object[]{kode,nomor,jenis,checkIn,checkOut,lamaNginap,total});
            }
            rs.close();
            conn.close();
            stmt.close();
            
            tabelData.setModel(model);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void clear(){
        // TODO add your handling code here:
        txtKode.setText("");
        txtnokmr.setText("");
        txtjenis.setText("");
        datein.setText("");
        dateout.setText("");
        txtlama.setText("");
        txttotal.setText("");
        
    }
    
    public void update(String kode, int nokmar, String jeniskmr, String checkin, String checkout,int lama, int total){
        try {
            Class.forName(JDBC_DRIVER);
   
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
 
            stmt = conn.createStatement();
            
            String sql = "UPDATE transaksi SET kd_kmr=?, no_kmr=?, jenis_kmr=?,check_in=?,check_oout=?,lama=?, total=? WHERE kd_kmr='"+kode+"'";
            
            PreparedStatement pms = conn.prepareStatement(sql);
            pms.setString(1, kode);
            pms.setInt(2, nokmar);
            pms.setString(3, jeniskmr);
            pms.setString(4, checkin);
            pms.setString(5, checkout);
            pms.setInt(6, lama);
            pms.setInt(7, total);
            
            pms.execute();
            
            stmt.close();
            conn.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }
    
    
public void total()
{
      int lama = Integer.parseInt(txtlama.getText());
      String jeniskmr = (String) txtbockam.getSelectedItem();

        // Menghitung total harga
        int hargaPerHari = 0;
        if (jeniskmr.equals("Single Room")) {
        hargaPerHari = 1000000;
        } else if (jeniskmr.equals("Deluxe Room")) {
        hargaPerHari = 2000000;
        } else if (jeniskmr.equals("Double Room")) {
        hargaPerHari = 3000000;
        } else if (jeniskmr.equals("Skuyy Room")) {
        hargaPerHari = 4000000;
    
    }
    int total = hargaPerHari * lama;
    txttotal.setText(String.valueOf(total));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datein;
    private javax.swing.JTextField dateout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelData;
    private javax.swing.JButton tblClear;
    private javax.swing.JButton tblDelete;
    private javax.swing.JButton tblUpdate;
    private javax.swing.JTextField txtKode;
    private javax.swing.JButton txtSimpan;
    private javax.swing.JComboBox<String> txtbockam;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtlama;
    private javax.swing.JTextField txtnokmr;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}

